-- Phase B: payout account rejection audit fields + payout notification types

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_INITIATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_PROCESSING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_ACCOUNT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_ACCOUNT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMISSION_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMISSION_OVERDUE';

ALTER TABLE "guide_payout_accounts" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "guide_payout_accounts" ADD COLUMN IF NOT EXISTS "rejectedBy" TEXT;
ALTER TABLE "guide_payout_accounts" ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3);
